DELETE http://localhost:3003/api/blogs/672fabbd2f76a97099b80206
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpcmRmaXJlIiwiaWQiOiI2NzJlN2JkNTg4OTJhYWI3MDQ4NDA4ZDQiLCJpYXQiOjE3MzM3NTY0MzQsImV4cCI6MTczMzc2MDAzNH0.IVLVG2U1UdXtNWzXzlFj5L-HtIV3m2hsKBAckp3bHEU